=== ISTIFANO/All_Exercices_Learning_php/projet_gestion_multimedia/Traitement_documents_XML/fichiers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- fichiers -->
  <xs:element name="fichiers">
    <xs:complexType>
      <xs:sequence>
        <!-- fichier -->
        <xs:element name="fichier" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="type" type="xs:string"/>
              <xs:element name="taille" type="xs:integer"/>
              <xs:element name="date_telechargement" type="xs:string"/>
            </xs:sequence>
            <!-- Attribut ID -->
            <xs:attribute name="id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- DÃ©finition du format de date YYYY-MM-DD HH:MM:SS -->
  <xs:simpleType name="dateType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== ISTIFANO/All_Exercices_Learning_php/fd/projet_gestion_multimedia/Traitement_documents_XML/fichiers.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet href="fichiers.xsl" type="text/xsl"?>
<fichiers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="fichiers.xsd">
    <fichier id='11'>
        <nom>Fichier6625737c072b79.73159182</nom>
        <type>document</type>
        <taille>17966</taille>
        <date_telechargement>2024-04-21 21:13:48</date_telechargement>
    </fichier>
    <fichier id='9'>
        <nom>Fichier66253ac7840099.14338050</nom>
        <type>image</type>
        <taille>208835</taille>
        <date_telechargement>2024-04-21 17:11:51</date_telechargement>
    </fichier>
    <fichier id='12'>
        <nom>Fichier662573845cf060.05907776</nom>
        <type>document</type>
        <taille>1175602</taille>
        <date_telechargement>2024-04-21 21:13:56</date_telechargement>
    </fichier>
</fichiers>
